import type { Metadata } from "next";
import { Manrope } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import GlobalcontextProvider from "./Context";
import Tranistion from "@/components/transitionEffect/Tranistion";

const inter = Manrope({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <GlobalcontextProvider>
        <Navbar />
        <Tranistion />
        {children}
        <Footer/>
        </GlobalcontextProvider>
        </body>
    </html>
  );
}
